#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

TARGET = Scaff
#CXX = clang++
#CFLAGS = -Werror=option-ignored
CXX = g++
CFLAGS = -Wall -fexceptions -Wpedantic -Wuninitialized -Wmissing-include-dirs -g 

$(TARGET): obj/main.o obj/FacadeScaff.o obj/Menus.o obj/Utilities.o
	$(CXX) -o $@ main.cpp src/FacadeScaff.cxx src/Menus.cxx  src/Utilities.cxx

main.o: src/main.cpp lib/FacadeScaff.hxx lib/Logger.hxx lib/Utilities.hxx
	$(CXX) $(CFLAGS) -c $<

FacadeScaff.o: src/FacadeScaff.cxx lib/FacadeScaff.hxx
	$(CXX) $(CFLAGS) -c $<
	
Logger.o: src/Logger.cxx lib/Logger.hxx
	$(CXX) $(CFLAGS) -c $<
	
Menus.o: src/Menus.cxx lib/Menus.hxx
	$(CXX) $(CFLAGS) -c $<

Utilities.o: src/Utilities.cxx lib/Utilities.hxx
	$(CXX) $(CFLAGS) -c $<

